// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: DriverLicenseValidator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_validators.go -package=mocks . DriverLicenseValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDriverLicenseValidator is a mock of DriverLicenseValidator interface.
type MockDriverLicenseValidator struct {
	ctrl     *gomock.Controller
	recorder *MockDriverLicenseValidatorMockRecorder
	isgomock struct{}
}

// MockDriverLicenseValidatorMockRecorder is the mock recorder for MockDriverLicenseValidator.
type MockDriverLicenseValidatorMockRecorder struct {
	mock *MockDriverLicenseValidator
}

// NewMockDriverLicenseValidator creates a new mock instance.
func NewMockDriverLicenseValidator(ctrl *gomock.Controller) *MockDriverLicenseValidator {
	mock := &MockDriverLicenseValidator{ctrl: ctrl}
	mock.recorder = &MockDriverLicenseValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverLicenseValidator) EXPECT() *MockDriverLicenseValidatorMockRecorder {
	return m.recorder
}

// ValidateLicense mocks base method.
func (m *MockDriverLicenseValidator) ValidateLicense(ctx context.Context, firstName, lastName, licenseNumber string) (domain.LicenseValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLicense", ctx, firstName, lastName, licenseNumber)
	ret0, _ := ret[0].(domain.LicenseValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateLicense indicates an expected call of ValidateLicense.
func (mr *MockDriverLicenseValidatorMockRecorder) ValidateLicense(ctx, firstName, lastName, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLicense", reflect.TypeOf((*MockDriverLicenseValidator)(nil).ValidateLicense), ctx, firstName, lastName, licenseNumber)
}
