// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: FeatureToggleProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_feature_toggles.go -package=mocks . FeatureToggleProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFeatureToggleProvider is a mock of FeatureToggleProvider interface.
type MockFeatureToggleProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureToggleProviderMockRecorder
	isgomock struct{}
}

// MockFeatureToggleProviderMockRecorder is the mock recorder for MockFeatureToggleProvider.
type MockFeatureToggleProviderMockRecorder struct {
	mock *MockFeatureToggleProvider
}

// NewMockFeatureToggleProvider creates a new mock instance.
func NewMockFeatureToggleProvider(ctrl *gomock.Controller) *MockFeatureToggleProvider {
	mock := &MockFeatureToggleProvider{ctrl: ctrl}
	mock.recorder = &MockFeatureToggleProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureToggleProvider) EXPECT() *MockFeatureToggleProviderMockRecorder {
	return m.recorder
}

// GetToggle mocks base method.
func (m *MockFeatureToggleProvider) GetToggle(ctx context.Context, name string) (*domain.FeatureToggle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToggle", ctx, name)
	ret0, _ := ret[0].(*domain.FeatureToggle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToggle indicates an expected call of GetToggle.
func (mr *MockFeatureToggleProviderMockRecorder) GetToggle(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToggle", reflect.TypeOf((*MockFeatureToggleProvider)(nil).GetToggle), ctx, name)
}

// IsEnabled mocks base method.
func (m *MockFeatureToggleProvider) IsEnabled(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockFeatureToggleProviderMockRecorder) IsEnabled(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockFeatureToggleProvider)(nil).IsEnabled), ctx, name)
}

// ListToggles mocks base method.
func (m *MockFeatureToggleProvider) ListToggles(ctx context.Context) ([]*domain.FeatureToggle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToggles", ctx)
	ret0, _ := ret[0].([]*domain.FeatureToggle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToggles indicates an expected call of ListToggles.
func (mr *MockFeatureToggleProviderMockRecorder) ListToggles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToggles", reflect.TypeOf((*MockFeatureToggleProvider)(nil).ListToggles), ctx)
}
