// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: FooEntityService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_services.go -package=mocks . FooEntityService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFooEntityService is a mock of FooEntityService interface.
type MockFooEntityService struct {
	ctrl     *gomock.Controller
	recorder *MockFooEntityServiceMockRecorder
	isgomock struct{}
}

// MockFooEntityServiceMockRecorder is the mock recorder for MockFooEntityService.
type MockFooEntityServiceMockRecorder struct {
	mock *MockFooEntityService
}

// NewMockFooEntityService creates a new mock instance.
func NewMockFooEntityService(ctrl *gomock.Controller) *MockFooEntityService {
	mock := &MockFooEntityService{ctrl: ctrl}
	mock.recorder = &MockFooEntityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooEntityService) EXPECT() *MockFooEntityServiceMockRecorder {
	return m.recorder
}

// CreateEntity mocks base method.
func (m *MockFooEntityService) CreateEntity(ctx context.Context, name, description string) (*domain.FooEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntity", ctx, name, description)
	ret0, _ := ret[0].(*domain.FooEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntity indicates an expected call of CreateEntity.
func (mr *MockFooEntityServiceMockRecorder) CreateEntity(ctx, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntity", reflect.TypeOf((*MockFooEntityService)(nil).CreateEntity), ctx, name, description)
}

// DeleteEntity mocks base method.
func (m *MockFooEntityService) DeleteEntity(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntity indicates an expected call of DeleteEntity.
func (mr *MockFooEntityServiceMockRecorder) DeleteEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntity", reflect.TypeOf((*MockFooEntityService)(nil).DeleteEntity), ctx, id)
}

// GetEntity mocks base method.
func (m *MockFooEntityService) GetEntity(ctx context.Context, id string) (*domain.FooEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntity", ctx, id)
	ret0, _ := ret[0].(*domain.FooEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntity indicates an expected call of GetEntity.
func (mr *MockFooEntityServiceMockRecorder) GetEntity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntity", reflect.TypeOf((*MockFooEntityService)(nil).GetEntity), ctx, id)
}

// ListEntities mocks base method.
func (m *MockFooEntityService) ListEntities(ctx context.Context) ([]*domain.FooEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntities", ctx)
	ret0, _ := ret[0].([]*domain.FooEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntities indicates an expected call of ListEntities.
func (mr *MockFooEntityServiceMockRecorder) ListEntities(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntities", reflect.TypeOf((*MockFooEntityService)(nil).ListEntities), ctx)
}
