// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: LegalEntityRepository,FleetRepository,VehicleRepository,DriverRepository,ContractRepository,VehicleAssignmentRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repositories.go -package=mocks . LegalEntityRepository,FleetRepository,VehicleRepository,DriverRepository,ContractRepository,VehicleAssignmentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLegalEntityRepository is a mock of LegalEntityRepository interface.
type MockLegalEntityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLegalEntityRepositoryMockRecorder
	isgomock struct{}
}

// MockLegalEntityRepositoryMockRecorder is the mock recorder for MockLegalEntityRepository.
type MockLegalEntityRepositoryMockRecorder struct {
	mock *MockLegalEntityRepository
}

// NewMockLegalEntityRepository creates a new mock instance.
func NewMockLegalEntityRepository(ctrl *gomock.Controller) *MockLegalEntityRepository {
	mock := &MockLegalEntityRepository{ctrl: ctrl}
	mock.recorder = &MockLegalEntityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegalEntityRepository) EXPECT() *MockLegalEntityRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockLegalEntityRepository) FindAll(ctx context.Context) ([]*domain.LegalEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.LegalEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockLegalEntityRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockLegalEntityRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockLegalEntityRepository) FindByID(ctx context.Context, id string) (*domain.LegalEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.LegalEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLegalEntityRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLegalEntityRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockLegalEntityRepository) Save(ctx context.Context, entity *domain.LegalEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLegalEntityRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLegalEntityRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockLegalEntityRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockLegalEntityRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockLegalEntityRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockLegalEntityRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockLegalEntityRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockLegalEntityRepository)(nil).Undelete), ctx, id)
}

// MockFleetRepository is a mock of FleetRepository interface.
type MockFleetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFleetRepositoryMockRecorder
	isgomock struct{}
}

// MockFleetRepositoryMockRecorder is the mock recorder for MockFleetRepository.
type MockFleetRepositoryMockRecorder struct {
	mock *MockFleetRepository
}

// NewMockFleetRepository creates a new mock instance.
func NewMockFleetRepository(ctrl *gomock.Controller) *MockFleetRepository {
	mock := &MockFleetRepository{ctrl: ctrl}
	mock.recorder = &MockFleetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetRepository) EXPECT() *MockFleetRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockFleetRepository) FindByID(ctx context.Context, id string) (*domain.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFleetRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFleetRepository)(nil).FindByID), ctx, id)
}

// FindByLegalEntityID mocks base method.
func (m *MockFleetRepository) FindByLegalEntityID(ctx context.Context, legalEntityID string) ([]*domain.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLegalEntityID", ctx, legalEntityID)
	ret0, _ := ret[0].([]*domain.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLegalEntityID indicates an expected call of FindByLegalEntityID.
func (mr *MockFleetRepositoryMockRecorder) FindByLegalEntityID(ctx, legalEntityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLegalEntityID", reflect.TypeOf((*MockFleetRepository)(nil).FindByLegalEntityID), ctx, legalEntityID)
}

// Save mocks base method.
func (m *MockFleetRepository) Save(ctx context.Context, entity *domain.Fleet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFleetRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFleetRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockFleetRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockFleetRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockFleetRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockFleetRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockFleetRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockFleetRepository)(nil).Undelete), ctx, id)
}

// MockVehicleRepository is a mock of VehicleRepository interface.
type MockVehicleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleRepositoryMockRecorder
	isgomock struct{}
}

// MockVehicleRepositoryMockRecorder is the mock recorder for MockVehicleRepository.
type MockVehicleRepositoryMockRecorder struct {
	mock *MockVehicleRepository
}

// NewMockVehicleRepository creates a new mock instance.
func NewMockVehicleRepository(ctrl *gomock.Controller) *MockVehicleRepository {
	mock := &MockVehicleRepository{ctrl: ctrl}
	mock.recorder = &MockVehicleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleRepository) EXPECT() *MockVehicleRepositoryMockRecorder {
	return m.recorder
}

// FindByFleetID mocks base method.
func (m *MockVehicleRepository) FindByFleetID(ctx context.Context, fleetID string) ([]*domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFleetID", ctx, fleetID)
	ret0, _ := ret[0].([]*domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFleetID indicates an expected call of FindByFleetID.
func (mr *MockVehicleRepositoryMockRecorder) FindByFleetID(ctx, fleetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFleetID", reflect.TypeOf((*MockVehicleRepository)(nil).FindByFleetID), ctx, fleetID)
}

// FindByID mocks base method.
func (m *MockVehicleRepository) FindByID(ctx context.Context, id string) (*domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVehicleRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVehicleRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockVehicleRepository) Save(ctx context.Context, entity *domain.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockVehicleRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVehicleRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockVehicleRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockVehicleRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockVehicleRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockVehicleRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockVehicleRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockVehicleRepository)(nil).Undelete), ctx, id)
}

// MockDriverRepository is a mock of DriverRepository interface.
type MockDriverRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriverRepositoryMockRecorder
	isgomock struct{}
}

// MockDriverRepositoryMockRecorder is the mock recorder for MockDriverRepository.
type MockDriverRepositoryMockRecorder struct {
	mock *MockDriverRepository
}

// NewMockDriverRepository creates a new mock instance.
func NewMockDriverRepository(ctrl *gomock.Controller) *MockDriverRepository {
	mock := &MockDriverRepository{ctrl: ctrl}
	mock.recorder = &MockDriverRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverRepository) EXPECT() *MockDriverRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockDriverRepository) FindAll(ctx context.Context) ([]*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDriverRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDriverRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockDriverRepository) FindByID(ctx context.Context, id string) (*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDriverRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDriverRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockDriverRepository) Save(ctx context.Context, entity *domain.Driver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDriverRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDriverRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockDriverRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockDriverRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockDriverRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockDriverRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockDriverRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockDriverRepository)(nil).Undelete), ctx, id)
}

// MockContractRepository is a mock of ContractRepository interface.
type MockContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractRepositoryMockRecorder
	isgomock struct{}
}

// MockContractRepositoryMockRecorder is the mock recorder for MockContractRepository.
type MockContractRepositoryMockRecorder struct {
	mock *MockContractRepository
}

// NewMockContractRepository creates a new mock instance.
func NewMockContractRepository(ctrl *gomock.Controller) *MockContractRepository {
	mock := &MockContractRepository{ctrl: ctrl}
	mock.recorder = &MockContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractRepository) EXPECT() *MockContractRepositoryMockRecorder {
	return m.recorder
}

// FindByDriverID mocks base method.
func (m *MockContractRepository) FindByDriverID(ctx context.Context, driverID string) ([]*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDriverID", ctx, driverID)
	ret0, _ := ret[0].([]*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDriverID indicates an expected call of FindByDriverID.
func (mr *MockContractRepositoryMockRecorder) FindByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDriverID", reflect.TypeOf((*MockContractRepository)(nil).FindByDriverID), ctx, driverID)
}

// FindByID mocks base method.
func (m *MockContractRepository) FindByID(ctx context.Context, id string) (*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockContractRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContractRepository)(nil).FindByID), ctx, id)
}

// FindOverlapping mocks base method.
func (m *MockContractRepository) FindOverlapping(ctx context.Context, driverID, legalEntityID, fleetID string, startDate, endDate time.Time, excludeID string) ([]*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverlapping", ctx, driverID, legalEntityID, fleetID, startDate, endDate, excludeID)
	ret0, _ := ret[0].([]*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOverlapping indicates an expected call of FindOverlapping.
func (mr *MockContractRepositoryMockRecorder) FindOverlapping(ctx, driverID, legalEntityID, fleetID, startDate, endDate, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverlapping", reflect.TypeOf((*MockContractRepository)(nil).FindOverlapping), ctx, driverID, legalEntityID, fleetID, startDate, endDate, excludeID)
}

// Save mocks base method.
func (m *MockContractRepository) Save(ctx context.Context, entity *domain.Contract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockContractRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockContractRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockContractRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockContractRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockContractRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockContractRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockContractRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockContractRepository)(nil).Undelete), ctx, id)
}

// MockVehicleAssignmentRepository is a mock of VehicleAssignmentRepository interface.
type MockVehicleAssignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleAssignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockVehicleAssignmentRepositoryMockRecorder is the mock recorder for MockVehicleAssignmentRepository.
type MockVehicleAssignmentRepositoryMockRecorder struct {
	mock *MockVehicleAssignmentRepository
}

// NewMockVehicleAssignmentRepository creates a new mock instance.
func NewMockVehicleAssignmentRepository(ctrl *gomock.Controller) *MockVehicleAssignmentRepository {
	mock := &MockVehicleAssignmentRepository{ctrl: ctrl}
	mock.recorder = &MockVehicleAssignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleAssignmentRepository) EXPECT() *MockVehicleAssignmentRepositoryMockRecorder {
	return m.recorder
}

// FindActiveByDriverID mocks base method.
func (m *MockVehicleAssignmentRepository) FindActiveByDriverID(ctx context.Context, driverID string) ([]*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDriverID", ctx, driverID)
	ret0, _ := ret[0].([]*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDriverID indicates an expected call of FindActiveByDriverID.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) FindActiveByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDriverID", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).FindActiveByDriverID), ctx, driverID)
}

// FindActiveByDriverIDAndFleetID mocks base method.
func (m *MockVehicleAssignmentRepository) FindActiveByDriverIDAndFleetID(ctx context.Context, driverID, fleetID string) (*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByDriverIDAndFleetID", ctx, driverID, fleetID)
	ret0, _ := ret[0].(*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByDriverIDAndFleetID indicates an expected call of FindActiveByDriverIDAndFleetID.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) FindActiveByDriverIDAndFleetID(ctx, driverID, fleetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByDriverIDAndFleetID", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).FindActiveByDriverIDAndFleetID), ctx, driverID, fleetID)
}

// FindByContractID mocks base method.
func (m *MockVehicleAssignmentRepository) FindByContractID(ctx context.Context, contractID string) ([]*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContractID", ctx, contractID)
	ret0, _ := ret[0].([]*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContractID indicates an expected call of FindByContractID.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) FindByContractID(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContractID", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).FindByContractID), ctx, contractID)
}

// FindByID mocks base method.
func (m *MockVehicleAssignmentRepository) FindByID(ctx context.Context, id string) (*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockVehicleAssignmentRepository) Save(ctx context.Context, entity *domain.VehicleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).Save), ctx, entity)
}

// SoftDelete mocks base method.
func (m *MockVehicleAssignmentRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).SoftDelete), ctx, id)
}

// Undelete mocks base method.
func (m *MockVehicleAssignmentRepository) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockVehicleAssignmentRepositoryMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockVehicleAssignmentRepository)(nil).Undelete), ctx, id)
}
