// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: FooEntityRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . FooEntityRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFooEntityRepository is a mock of FooEntityRepository interface.
type MockFooEntityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFooEntityRepositoryMockRecorder
	isgomock struct{}
}

// MockFooEntityRepositoryMockRecorder is the mock recorder for MockFooEntityRepository.
type MockFooEntityRepositoryMockRecorder struct {
	mock *MockFooEntityRepository
}

// NewMockFooEntityRepository creates a new mock instance.
func NewMockFooEntityRepository(ctrl *gomock.Controller) *MockFooEntityRepository {
	mock := &MockFooEntityRepository{ctrl: ctrl}
	mock.recorder = &MockFooEntityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooEntityRepository) EXPECT() *MockFooEntityRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFooEntityRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFooEntityRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFooEntityRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockFooEntityRepository) FindAll(ctx context.Context) ([]*domain.FooEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.FooEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockFooEntityRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockFooEntityRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockFooEntityRepository) FindByID(ctx context.Context, id string) (*domain.FooEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.FooEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFooEntityRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFooEntityRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockFooEntityRepository) Save(ctx context.Context, entity *domain.FooEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFooEntityRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFooEntityRepository)(nil).Save), ctx, entity)
}
