// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/albenik/uber-fx-based-service-example/internal/core/ports (interfaces: LegalEntityService,FleetService,VehicleService,DriverService,ContractService,VehicleAssignmentService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_services.go -package=mocks . LegalEntityService,FleetService,VehicleService,DriverService,ContractService,VehicleAssignmentService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/albenik/uber-fx-based-service-example/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLegalEntityService is a mock of LegalEntityService interface.
type MockLegalEntityService struct {
	ctrl     *gomock.Controller
	recorder *MockLegalEntityServiceMockRecorder
	isgomock struct{}
}

// MockLegalEntityServiceMockRecorder is the mock recorder for MockLegalEntityService.
type MockLegalEntityServiceMockRecorder struct {
	mock *MockLegalEntityService
}

// NewMockLegalEntityService creates a new mock instance.
func NewMockLegalEntityService(ctrl *gomock.Controller) *MockLegalEntityService {
	mock := &MockLegalEntityService{ctrl: ctrl}
	mock.recorder = &MockLegalEntityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegalEntityService) EXPECT() *MockLegalEntityServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLegalEntityService) Create(ctx context.Context, name, taxID string) (*domain.LegalEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, taxID)
	ret0, _ := ret[0].(*domain.LegalEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLegalEntityServiceMockRecorder) Create(ctx, name, taxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLegalEntityService)(nil).Create), ctx, name, taxID)
}

// Delete mocks base method.
func (m *MockLegalEntityService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLegalEntityServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLegalEntityService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockLegalEntityService) Get(ctx context.Context, id string) (*domain.LegalEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.LegalEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLegalEntityServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLegalEntityService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockLegalEntityService) List(ctx context.Context) ([]*domain.LegalEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.LegalEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLegalEntityServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLegalEntityService)(nil).List), ctx)
}

// Undelete mocks base method.
func (m *MockLegalEntityService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockLegalEntityServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockLegalEntityService)(nil).Undelete), ctx, id)
}

// MockFleetService is a mock of FleetService interface.
type MockFleetService struct {
	ctrl     *gomock.Controller
	recorder *MockFleetServiceMockRecorder
	isgomock struct{}
}

// MockFleetServiceMockRecorder is the mock recorder for MockFleetService.
type MockFleetServiceMockRecorder struct {
	mock *MockFleetService
}

// NewMockFleetService creates a new mock instance.
func NewMockFleetService(ctrl *gomock.Controller) *MockFleetService {
	mock := &MockFleetService{ctrl: ctrl}
	mock.recorder = &MockFleetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetService) EXPECT() *MockFleetServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFleetService) Create(ctx context.Context, legalEntityID, name string) (*domain.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, legalEntityID, name)
	ret0, _ := ret[0].(*domain.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFleetServiceMockRecorder) Create(ctx, legalEntityID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFleetService)(nil).Create), ctx, legalEntityID, name)
}

// Delete mocks base method.
func (m *MockFleetService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFleetServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFleetService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockFleetService) Get(ctx context.Context, id string) (*domain.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFleetServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFleetService)(nil).Get), ctx, id)
}

// ListByLegalEntity mocks base method.
func (m *MockFleetService) ListByLegalEntity(ctx context.Context, legalEntityID string) ([]*domain.Fleet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLegalEntity", ctx, legalEntityID)
	ret0, _ := ret[0].([]*domain.Fleet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLegalEntity indicates an expected call of ListByLegalEntity.
func (mr *MockFleetServiceMockRecorder) ListByLegalEntity(ctx, legalEntityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLegalEntity", reflect.TypeOf((*MockFleetService)(nil).ListByLegalEntity), ctx, legalEntityID)
}

// Undelete mocks base method.
func (m *MockFleetService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockFleetServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockFleetService)(nil).Undelete), ctx, id)
}

// MockVehicleService is a mock of VehicleService interface.
type MockVehicleService struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleServiceMockRecorder
	isgomock struct{}
}

// MockVehicleServiceMockRecorder is the mock recorder for MockVehicleService.
type MockVehicleServiceMockRecorder struct {
	mock *MockVehicleService
}

// NewMockVehicleService creates a new mock instance.
func NewMockVehicleService(ctrl *gomock.Controller) *MockVehicleService {
	mock := &MockVehicleService{ctrl: ctrl}
	mock.recorder = &MockVehicleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleService) EXPECT() *MockVehicleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVehicleService) Create(ctx context.Context, fleetID, make, model, licensePlate string, year int) (*domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, fleetID, make, model, licensePlate, year)
	ret0, _ := ret[0].(*domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVehicleServiceMockRecorder) Create(ctx, fleetID, make, model, licensePlate, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVehicleService)(nil).Create), ctx, fleetID, make, model, licensePlate, year)
}

// Delete mocks base method.
func (m *MockVehicleService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVehicleServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVehicleService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockVehicleService) Get(ctx context.Context, id string) (*domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVehicleServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVehicleService)(nil).Get), ctx, id)
}

// ListByFleet mocks base method.
func (m *MockVehicleService) ListByFleet(ctx context.Context, fleetID string) ([]*domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFleet", ctx, fleetID)
	ret0, _ := ret[0].([]*domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFleet indicates an expected call of ListByFleet.
func (mr *MockVehicleServiceMockRecorder) ListByFleet(ctx, fleetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFleet", reflect.TypeOf((*MockVehicleService)(nil).ListByFleet), ctx, fleetID)
}

// Undelete mocks base method.
func (m *MockVehicleService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockVehicleServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockVehicleService)(nil).Undelete), ctx, id)
}

// MockDriverService is a mock of DriverService interface.
type MockDriverService struct {
	ctrl     *gomock.Controller
	recorder *MockDriverServiceMockRecorder
	isgomock struct{}
}

// MockDriverServiceMockRecorder is the mock recorder for MockDriverService.
type MockDriverServiceMockRecorder struct {
	mock *MockDriverService
}

// NewMockDriverService creates a new mock instance.
func NewMockDriverService(ctrl *gomock.Controller) *MockDriverService {
	mock := &MockDriverService{ctrl: ctrl}
	mock.recorder = &MockDriverServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverService) EXPECT() *MockDriverServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDriverService) Create(ctx context.Context, firstName, lastName, licenseNumber string) (*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, firstName, lastName, licenseNumber)
	ret0, _ := ret[0].(*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDriverServiceMockRecorder) Create(ctx, firstName, lastName, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriverService)(nil).Create), ctx, firstName, lastName, licenseNumber)
}

// Delete mocks base method.
func (m *MockDriverService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDriverServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDriverService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockDriverService) Get(ctx context.Context, id string) (*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDriverServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDriverService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockDriverService) List(ctx context.Context) ([]*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDriverServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDriverService)(nil).List), ctx)
}

// Undelete mocks base method.
func (m *MockDriverService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockDriverServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockDriverService)(nil).Undelete), ctx, id)
}

// MockContractService is a mock of ContractService interface.
type MockContractService struct {
	ctrl     *gomock.Controller
	recorder *MockContractServiceMockRecorder
	isgomock struct{}
}

// MockContractServiceMockRecorder is the mock recorder for MockContractService.
type MockContractServiceMockRecorder struct {
	mock *MockContractService
}

// NewMockContractService creates a new mock instance.
func NewMockContractService(ctrl *gomock.Controller) *MockContractService {
	mock := &MockContractService{ctrl: ctrl}
	mock.recorder = &MockContractServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractService) EXPECT() *MockContractServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContractService) Create(ctx context.Context, driverID, legalEntityID, fleetID string, startDate, endDate time.Time) (*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, driverID, legalEntityID, fleetID, startDate, endDate)
	ret0, _ := ret[0].(*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContractServiceMockRecorder) Create(ctx, driverID, legalEntityID, fleetID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContractService)(nil).Create), ctx, driverID, legalEntityID, fleetID, startDate, endDate)
}

// Delete mocks base method.
func (m *MockContractService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContractServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContractService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockContractService) Get(ctx context.Context, id string) (*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContractServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContractService)(nil).Get), ctx, id)
}

// ListByDriver mocks base method.
func (m *MockContractService) ListByDriver(ctx context.Context, driverID string) ([]*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDriver", ctx, driverID)
	ret0, _ := ret[0].([]*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDriver indicates an expected call of ListByDriver.
func (mr *MockContractServiceMockRecorder) ListByDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDriver", reflect.TypeOf((*MockContractService)(nil).ListByDriver), ctx, driverID)
}

// Terminate mocks base method.
func (m *MockContractService) Terminate(ctx context.Context, id, terminatedBy string) (*domain.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx, id, terminatedBy)
	ret0, _ := ret[0].(*domain.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Terminate indicates an expected call of Terminate.
func (mr *MockContractServiceMockRecorder) Terminate(ctx, id, terminatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockContractService)(nil).Terminate), ctx, id, terminatedBy)
}

// Undelete mocks base method.
func (m *MockContractService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockContractServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockContractService)(nil).Undelete), ctx, id)
}

// MockVehicleAssignmentService is a mock of VehicleAssignmentService interface.
type MockVehicleAssignmentService struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleAssignmentServiceMockRecorder
	isgomock struct{}
}

// MockVehicleAssignmentServiceMockRecorder is the mock recorder for MockVehicleAssignmentService.
type MockVehicleAssignmentServiceMockRecorder struct {
	mock *MockVehicleAssignmentService
}

// NewMockVehicleAssignmentService creates a new mock instance.
func NewMockVehicleAssignmentService(ctrl *gomock.Controller) *MockVehicleAssignmentService {
	mock := &MockVehicleAssignmentService{ctrl: ctrl}
	mock.recorder = &MockVehicleAssignmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleAssignmentService) EXPECT() *MockVehicleAssignmentServiceMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockVehicleAssignmentService) Assign(ctx context.Context, contractID, vehicleID string) (*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, contractID, vehicleID)
	ret0, _ := ret[0].(*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockVehicleAssignmentServiceMockRecorder) Assign(ctx, contractID, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockVehicleAssignmentService)(nil).Assign), ctx, contractID, vehicleID)
}

// Delete mocks base method.
func (m *MockVehicleAssignmentService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVehicleAssignmentServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVehicleAssignmentService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockVehicleAssignmentService) Get(ctx context.Context, id string) (*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVehicleAssignmentServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVehicleAssignmentService)(nil).Get), ctx, id)
}

// ListByContract mocks base method.
func (m *MockVehicleAssignmentService) ListByContract(ctx context.Context, contractID string) ([]*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByContract", ctx, contractID)
	ret0, _ := ret[0].([]*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByContract indicates an expected call of ListByContract.
func (mr *MockVehicleAssignmentServiceMockRecorder) ListByContract(ctx, contractID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByContract", reflect.TypeOf((*MockVehicleAssignmentService)(nil).ListByContract), ctx, contractID)
}

// Return mocks base method.
func (m *MockVehicleAssignmentService) Return(ctx context.Context, id string) (*domain.VehicleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Return", ctx, id)
	ret0, _ := ret[0].(*domain.VehicleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Return indicates an expected call of Return.
func (mr *MockVehicleAssignmentServiceMockRecorder) Return(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Return", reflect.TypeOf((*MockVehicleAssignmentService)(nil).Return), ctx, id)
}

// Undelete mocks base method.
func (m *MockVehicleAssignmentService) Undelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undelete indicates an expected call of Undelete.
func (mr *MockVehicleAssignmentServiceMockRecorder) Undelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undelete", reflect.TypeOf((*MockVehicleAssignmentService)(nil).Undelete), ctx, id)
}
